molgenis/molgenis-app-lifelines-webshop

nightwatch.config.js, package.json, yarn.lock
Switch back to 'old' cli version setup as new ( 1.x nightwatch version) does not run in current CI pipline.
=> switch to stable cli 3 version

src/App.vue, src/components/grid/GridComponent.vue, src/router.ts, src/store/actions.ts, src/store/helpers.ts, src/store/mutations.ts, src/types/ApplicationState.ts, src/types/Cart.ts, src/types/Filter.ts, src/views/MainView.vue, tests/unit/store/actions.spec.ts, tests/unit/views/MainView.spec.ts
Was a bit more intricate than I initially thought because the grid selection in the store is `{[variableId]: [assessmentId]}` and the structure in the cart is `{assessmentName, variables: [variableName]}`.
So we need to convert both id to name and back again and switch from grouping by variable to grouping by assessment and back again.
I've assumed that the facet filters can be copied over unchanged from the store but this may be mistaken because in the store we also have keys for empty filters.
=> feat: load and save orders in the agreed upon format

src/components/tree/CollapsibleTree.vue, src/store/mutations.ts, src/views/TreeView.vue, tests/unit/components/tree/CollapsibleTree.spec.ts, tests/unit/views/TreeView.spec.ts
Tree component state of opened section is persisted via vuex
- Externalized opened section state to the TreeView.vue
- Bound the tree component to the store in TreeView.vue
- Redone the tests
=> feat: store tree state

src/components/facets/FacetContainer.vue
Buttons edges, bars and popups have a little more room to the sides.
(Year of birth slider was partially hidden by `overflow:hidden`)
=> fix: Facet container partial visible

src/store/actions.ts, src/store/getters.ts, src/store/mutations.ts, src/store/state.ts, src/types/ApplicationState.ts, src/types/Getters.ts, src/types/TreeNode.ts, src/views/ContentView.vue, src/views/TreeView.vue, tests/unit/store/actions.spec.ts, tests/unit/store/getters.spec.ts, tests/unit/store/mutations.spec.ts, tests/unit/views/ContentView.spec.ts, tests/unit/views/TreeView.spec.ts
First commit changes only the store (everything is null if it is not currently active):
* `state.searchTerm` contains the search term. I assumed it is a single string to keep things simple.
* `getters.searchTermQuery` transforms it to search criteria. I've picked a first simple `*=q=${searchTerm}`. If folks want more we can update this to e.g. convert search string `'foo bar'` to `*=q='foo',*=q='bar'`
* `state.filteredSections` contains the IDs of sections that match the search term
* `state.filteredSubsections` contains the IDs of subsections that either
* match the search term or 
* contain variables that match the search term
* `actions.filterSections` and `actions.filterSubsections` fetch these arrays using the `searchTermQuery`
* `getters.filteredTreeStructure` filters …
=> feat(store): filter tree and variables

src/components/animations/BlockExpand.vue
Fixes: 
TreeView does not like it if we update the tree when it's expanded. Some of the nodes end up with weird height
Searching with tree open did not update height of element. Now the element is height: auto by default.
=> Fix(BlockExpand) will now not force height

src/components/grid/GridComponent.vue
Grid table header wil stay in its place now
- Code unit/integration/system tested - is dependant on #70
=> fix sticky headers #72

i18n.schemas.js, src/components/grid/GridComponent.vue, src/store/state.ts, src/types/ApplicationState.ts, src/views/CartView.vue, src/views/ContentView.vue, src/views/GridView.vue, tests/unit/components/grid/GridComponent.spec.ts, tests/unit/views/CartView.spec.ts, tests/unit/views/ContentView.spec.ts, tests/unit/views/GridView.spec.ts
- add signed in flag to store
- remove add add/row/col variable buttons when not signed in
- remove click handler from grid when not signed in
- change headers depending of whether user is signed in
=> feat: read only mode for anonymous user

src/components/tree/CollapsibleTree.vue, src/store/actions.ts, src/store/getters.ts, src/store/mutations.ts, src/types/ApplicationState.ts, src/types/Tree.ts, tests/unit/store/getters.spec.ts, tests/unit/store/mutations.spec.ts
The relationship between variable selection and section selection
count is complicated.
You need to know the complete subsection<->variable details
if you want to relate selection to counts.
This is 17000 rows to fetch.
We choose not to.
=> fix: remove counts and selection dots from tree

src/store/actions.ts
First set the order to the state, then use the oderNumber to update the permissions
=> fix: Closes #158 Set orderNumber to state before using it

src/store/getters.ts, src/store/store.ts, src/types/ApplicationState.ts, tests/unit/fixtures/state.ts, tests/unit/store/actions.spec.ts, tests/unit/store/getters.spec.ts, tests/unit/store/helpers.spec.ts, tests/unit/store/mutations.spec.ts, tests/unit/store/state.spec.ts, tests/unit/views/CountView.spec.ts, tests/unit/views/MainView.spec.ts, tests/unit/views/SidebarView.spec.ts
We only start using the store once the context is loaded.
Update typings to reflect this
The benefit is that the typescript checker will know that the context is always available and will not make you do lots of null checks.
=> refactor: fix typings

src/views/TreeView.vue
=> fix: use min-width for tree-view(IE11)

src/services/permissionService.ts, src/store/actions.ts, src/store/mutations.ts, src/store/state.ts, src/types/Order.ts, tests/unit/fixtures/orders.ts, tests/unit/services/permissionService.spec.ts, tests/unit/store/actions.spec.ts, tests/unit/store/mutations.spec.ts
Give back permissions to order creator, in case update
user is not the creator/manager. The following rights
are adjusted:
* Order
* Cart data
* Application form
=> fix: retain cart permission for user

src/store/actions.ts, src/views/OrdersView.vue, tests/unit/store/actions.spec.ts, tests/unit/store/helpers.spec.ts, tests/unit/views/__snapshots__/OrdersView.spec.ts.snap
- Give admin permission on cart contents file on submit
- Remove giving permission on oder back to user when admin saves order ( it's not needed and fails )
- When admin makes a copy have the creator ( shopper ) permission on the copy
- Always show edit button if user is admin
- Always shop delete button if user is admin
=> fix: order permissions

vue.config.js
Test with:
/usr/bin/chromium %U --remote-debugging-port=9222
Set a breakpoint in vscode and start debugging. Breakpoints are now properly hit and stepping works as expected. Also, while inspecting styles in the browser, it will list the proper source.
=> chore: add sourcemap support for vue, ts & scss

src/components/grid/GridComponent.vue
Small bug: currently variables sets starts closed, but going to the cart and back opens it.
=> fix: make sure the variable set starts closed

src/views/SidebarView.vue
testcase:
cohort selection doesn't close when clicking outside. Only on the [<<] button
=> feat: only hide cohort selection when user clicks on the button

src/components/grid/GridInfoDialog.vue, src/repository/VariableRepository.ts, src/types/Variable.ts, tests/unit/repository/VariableRepository.spec.ts, tests/unit/store/getters.spec.ts, tests/unit/store/helpers.spec.ts, tests/unit/store/mutations.spec.ts
=> fix: add definition_en & definition_nl to Variable definition

src/components/grid/GridComponent.vue, tests/unit/services/variableSetOrderService.spec.ts
Closes: #278
When horizontal scrollbar is shown compansate for offset due to scroll bar
This is needed due to use of absolute positioning used for foating header
=> fix: fix 278 Grid header alignment is off

src/store/actions.ts, tests/unit/store/actions.spec.ts
=> fix: add missing context param to sendAproveTrigger action

src/components/grid/GridComponent.vue
Closes #300 
- call recalculate offset of header after collapse open/close
=> fix: Fix header position for collapse vars

src/views/OrdersView.vue
=> fix: use trailing slash on vuepdf endpoint

src/store/actions.ts, src/types/Order.ts, tests/unit/store/actions.spec.ts
Closes #314
When a order is saved a new cart row is created
When the admin saves a order the order user should get permission on the cart
When the admin saves a order with file the user should also get permission on the file
When the admin save a order without file ( like approve ) the permission call for the file should not be made
=> fix: 314 error during approve

package.json, vue.config.js
Closes #329
Closes #330
Closes #331
- Add version to build path
- Call build script in npm post version hook to use correct version number
=> fix: #329 Cannot view old app version via browser url

src/components/grid/GridComponent.vue
Improve UX, do not let popover cover the 'plus' icon
=> fix: hover above instead of left

src/store/actions.ts, tests/unit/store/actions.spec.ts
Only remove the loading indicator when search has completed
Search may be completed by a different request then the one that set up the indicator
=> fix: loading indicator is removed if query is outdated by other query

tests/unit/services/variableSetOrderService.spec.ts
Trigger release off previous commit fix: cart variable order sorting
- Remove sub variable indicator from cart view
- Sort variables and sub variables alphabetically
=> fix: fix cart variable  order

src/store/getters.ts, tests/unit/components/search/SearchComponent.spec.ts, tests/unit/store/getters.spec.ts
Include list of active assessments in call to determine grid assessments.
As a result the grid columns get filtered, and as a result of that the now empty rows get hidden
=> feat: #7702 hide empty rows ( due to assessment filter )

src/store/actions.ts, tests/unit/store/actions.spec.ts
Sends post to edge server, '/submit' endpoint, passing the orderNumber
=> feat: Send trigger for notification on order submit

src/store/actions.ts, tests/unit/store/actions.spec.ts
On save a new file get created for the cart ( and optionaly a new application form)
The users in the role lifelines_MANAGER should be able to read/write these files
closes #364
=> fix: 364 Set file permissions on save

src/store/actions.ts, src/views/OrdersView.vue, tests/unit/store/actions.spec.ts
All variables are needed in the frontend to resolve cart ids.
This does not scale well to > 10000 variables
Not fetching all the variable details has implications for UX however ( viewing cart, column select, responsive feel ( once loaded)
Untill we desicde what to do about the UX , this PR makes sure the first 30000 variables are fetched.
=> fix; Apply band aid for missing variable issue

src/components/tree/CollapsibleTree.vue, src/store/actions.ts, src/store/getters.ts, src/store/mutations.ts, src/store/state.ts, src/store/transforms.ts, src/types/ApplicationState.ts, src/types/SubSection.ts, src/views/ContentView.vue, tests/unit/store/actions.spec.ts, tests/unit/store/getters.spec.ts, tests/unit/store/mutations.spec.ts, tests/unit/views/ContentView.spec.ts
If the wiki contains addtional information about a subsection add a link to view the wiki data
- refactor subsection from id to object to accommodate for link info
=> feat: Show wiki link for subsections

src/store/actions.ts
=> fix: add 'sec' to default selected assessments

src/views/CartView.vue, src/views/MainView.vue
- If user is not signed in the vars do not need to be loaded upfront, vars are loaded during section selection or search
- If the user is signed in the vars are loaded to render the cart
=> fix: Improve performance, only load vars when needed

src/views/CartView.vue, src/views/MainView.vue, tests/unit/views/CartView.spec.ts, tests/unit/views/MainView.spec.ts
Watch the active tab and show/hide loading message when appropriate
=> fix: cart spinner does not hide when loading is completed
