molgenis/molgenis-app-lifelines-webshop

src/views/ContentView.vue
src/views/MainView.vue
src/views/SidebarView.vue
tests/unit/ContentView.spec.ts
tests/unit/MainView.spec.ts
tests/unit/SidebarView.spec.ts

Added content en sidebar view

---

Jenkinsfile
nightwatch.config.js

try to fix ci setup , just run chrome on ci for now

---

src/store/state.ts
src/store/store.ts
src/types/applicationState.ts
src/views/SidebarView.vue
tests/unit/views/SidebarView.spec.ts

add actual subcohorts and rename cohorts to subcohorts

add subcohorts as described supplied by data owner

---

tests/unit/views/SidebarView.spec.ts

task: fix lint issues, via auto fixer

---

src/App.vue

demo branch

---

src/components/Grid/GridComponent.vue

feat(GridComponent): Add rotated grid labels

---

tests/unit/store/mutations.spec.ts

add unit tests for facet mutations

---

src/components/Grid/GridComponent.vue

feat(grid): Add loading spinner to grid

---

src/components/Grid/GridComponent.vue
src/store/actions.ts
src/store/mutations.ts
src/views/MainView.vue
tests/unit/store/actions.spec.ts
tests/unit/store/mutations.spec.ts

feat: load and save grid selections

---

Jenkinsfile
src/store/mutations.ts
tests/unit/store/mutations.spec.ts

If the last assessment has been deselected,
remove the variable from the selection.

fix(mutations): remove variable from selection

---

src/store/actions.ts
tests/unit/store/actions.spec.ts

chore(actions): rename cart entity type

---

src/store/actions.ts
src/views/MainView.vue
tests/unit/store/actions.spec.ts

fix issues

---

src/components/grid/GridComponent.vue

fix(grid): Remove height to make spinner smaller in firefox

---

tests/unit/views/CartView.spec.ts

fix(cart): fix test , remove extra whitespace

---

src/store/actions.ts
tests/unit/store/actions.spec.ts

Make sure that the data you've retrieved is still relevant before committing it

Fix mutation order

---

package.json
src/components/grid/GridComponent.vue
yarn.lock

refactor(grid): Replace spinner

---

src/store/actions.ts
tests/unit/store/actions.spec.ts

fix(actions): sort variables

---

src/store/helpers.ts
src/types/Cart.ts
tests/unit/store/actions.spec.ts
tests/unit/store/helpers.spec.ts

fix(helpers): use correct filter format in cart

---

src/components/animations/BlockExpand.vue
src/components/facets/AgeFacet.vue
src/components/facets/RangeFacet.vue
src/components/grid/GridComponent.vue
src/components/tree/CollapsibleTree.vue
src/scss/bootstrap-lifelines-webshop.scss

- Changed css variables to sass variables (ie11 compatibility)
- Consistent css style

Consistent css style and scss variables

---

package.json
src/components/grid/GridComponent.vue
src/main.ts
src/store/actions.ts
src/store/mutations.ts
src/store/state.ts
src/types/ApplicationState.ts
src/views/CountView.vue
src/views/SidebarView.vue
tests/unit/store/actions.spec.ts
tests/unit/store/mutations.spec.ts
tests/unit/views/CountView.spec.ts
tests/unit/views/SidebarView.spec.ts
yarn.lock

feat: show participant count

---

README.md
deployment/lifelines
package.json
src/router.ts
src/views/MainView.vue
vue.config.js

(feat): add build config

---

Jenkinsfile
package.json
yarn.lock

It will be publish when merging with the master. The release will be based on the conventional commits.

build(npx): add npx to publish the package

---

src/components/grid/GridComponent.vue
src/scss/bootstrap-lifelines-webshop.scss
tests/unit/components/grid/GridComponent.spec.ts

- move grid css from glocal css to component css
not finished, but suggest to further refactor ( try to use css instead of js where possible) before adding more tests

setup for grid component test

---

src/components/tree/CollapsibleTree.vue
src/scss/variables.scss
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/types/ApplicationState.ts
src/types/Getters.ts
src/types/Tree.ts
src/views/ContentView.vue
src/views/GridView.vue
tests/unit/components/tree/CollapsibleTree.spec.ts
tests/unit/store/getters.spec.ts
tests/unit/store/mutations.spec.ts
tests/unit/views/GridView.spec.ts
tests/unit/views/TreeView.spec.ts

- Selection of a variable will now add a reminder in the menu
- Used id's to select instead of name's

Show selections in tree

---

Jenkinsfile

build(Jenkinsfile): add build target to master step

---

vue.config.js

- Code unit/integration/system tested

feat: file name hashing, put it back so users get the new version

---

i18n.schemas.js
package.json
src/components/facets/FacetContainer.vue
src/components/grid/GridComponent.vue
src/components/search/SearchComponent.vue
src/components/tree/CollapsibleTree.vue
src/scss/bootstrap-lifelines-webshop.scss
src/store/mutations.ts
src/store/state.ts
src/types/ApplicationState.ts
src/views/CartView.vue
src/views/ContentView.vue
src/views/CountView.vue
src/views/GridView.vue
src/views/MainView.vue
src/views/SidebarView.vue
tests/e2e/specs/MainView.js
tests/unit/components/grid/GridComponent.spec.ts
tests/unit/components/search/SearchComponent.spec.ts
tests/unit/store/mutations.spec.ts
tests/unit/views/CartView.spec.ts
tests/unit/views/ContentView.spec.ts
tests/unit/views/GridView.spec.ts
tests/unit/views/MainView.spec.ts
tests/unit/views/SidebarView.spec.ts
yarn.lock

Align components

---

deployment/lifelines

chore(bootstrap server): import data into a molgenis instance

---

vue.config.js

task: change default dev server url back to lifelines.test.molgenis.org

---

package.json
src/App.vue
src/components/grid/GridComponent.vue
src/components/tree/CollapsibleTree.vue
src/scss/bootstrap-lifelines-webshop.scss
src/views/ContentView.vue
src/views/GridView.vue
src/views/MainView.vue
src/views/SidebarView.vue
src/views/TreeView.vue
tests/e2e/resources/uiContext.js
tests/unit/components/grid/GridComponent.spec.ts
tests/unit/views/MainView.spec.ts
tests/unit/views/TreeView.spec.ts
vue.config.js
yarn.lock

feat: add molgenis menu and footer

---

vue.config.js

chore: don't stub the server in dev mode

---

package.json
yarn.lock

task: workaround for outdated chromedriver

---

Jenkinsfile

task: release on master merge, remove manual step

---

src/router.ts

fix: production build base url path

---

src/router.ts
tests/e2e/specs/MainView.js

add index.html to router base path

---

deployment/lifelines

Set read permissions for uses that are not signed in so they can browse the store, but not submit an order.
Set write cart permissions for signed in user so they can submit an order.
- Functionality works & meets specifications
- Code unit/integration/system tested

task: setup app permissions

---

src/components/grid/GridComponent.vue
tests/unit/components/grid/GridComponent.spec.ts

Fix grid select all

---

README.md

docs(commander-run): updated command for commander run

---

src/store/actions.ts
src/views/OrderView.vue
tests/unit/store/actions.spec.ts
tests/unit/views/OrderView.spec.ts

Feat/add submit order btn to OrderView

---

src/router.ts

My order menu item does not link to myorders page.

fix: #118 change to hash-based routing

---

deployment/lifelines

fix(mcmd): Give write permissions on filemeta

---

vue.config.js

fix: #136 apply lifelines config defaults

---

src/views/GridView.vue
tests/unit/store/mutations.spec.ts
tests/unit/views/GridView.spec.ts

fix: fix #139 remove call to removed mutation

---

package.json
yarn.lock

task: bump molgenis-ui-context

---

src/store/actions.ts
src/views/OrderView.vue
tests/unit/store/actions.spec.ts
tests/unit/views/OrderView.spec.ts

- transform fileRef to string before use in form

fix: Update order with file data

---

.lifelinesrc.example
vue.config.js

chore: proxy server on dev custer

---

src/views/MainView.vue
tests/unit/views/MainView.spec.ts

feat: add cart badge

---

babel.config.js
package.json
public/index.html
src/main.ts
yarn.lock

fix: add polyfills for closest and findindex to IE11

---

package.json
src/store/actions.ts
tests/unit/store/actions.spec.ts
yarn.lock

feat: call edge server for trigger on submit

---

package.json
src/store/actions.ts
tests/unit/fixtures/state.ts
tests/unit/store/getters.spec.ts
tests/unit/store/state.spec.ts
yarn.lock

feat: add email and username to order

---

src/App.vue
src/scss/bootstrap-lifelines-webshop.scss
src/store/mutations.ts
src/store/state.ts
src/types/ApplicationState.ts
src/views/MainView.vue
tests/unit/views/MainView.spec.ts

feat: add global loader

---

src/store/helpers.ts

fix: use lookup map to load grid selection

---

src/components/grid/GridComponent.vue

fix: check grid array length instead of null value

---

src/components/grid/GridComponent.vue

fix: fix code style

---

.eslintrc.js
package.json

fix: rollback to using vue-cli lint command, closes #186

---

deployment/datasets/sys_L10nString.csv
i18n.schemas.js
package.json
src/store/getters.ts
src/views/OrdersView.vue
tests/unit/components/search/SearchComponent.spec.ts
tests/unit/fixtures/state.ts
tests/unit/store/getters.spec.ts
tests/unit/views/OrdersView.spec.ts
tests/unit/views/__snapshots__/OrdersView.spec.ts.snap
yarn.lock

feat:add email to order view for datamanager

---

deployment/datasets/sys_L10nString.csv

removed max and als of his monsters

Renamed project-label

---

.vscode/settings.json
src/views/CartView.vue
tests/unit/views/CartView.spec.ts
tests/unit/views/__snapshots__/CartView.spec.ts.snap

feat: open and close cart sections

---

src/components/grid/GridComponent.vue
src/components/grid/GridInfoDialog.vue
src/store/actions.ts
tests/unit/components/grid/GridInfoDialog.spec.ts
tests/unit/store/actions.spec.ts

fix: add live data

---

src/store/actions.ts
tests/unit/store/actions.spec.ts

fix: use underscores for label and definition

---

deployment/datasets/sys_L10nString.csv
i18n.schemas.js
src/scss/variables.scss
src/views/CartView.vue
src/views/OrderView.vue
src/views/SidebarView.vue
tests/unit/views/__snapshots__/CartView.spec.ts.snap

Empty variable warning

---

src/components/search/SearchComponent.vue
src/main.ts
src/store/actions.ts
src/store/getters.ts
src/types/Getters.ts
src/views/ContentView.vue
src/views/GridView.vue
src/views/TreeView.vue
tests/unit/store/actions.spec.ts
tests/unit/store/getters.spec.ts
tests/unit/views/GridView.spec.ts
tests/unit/views/OrdersView.spec.ts
tests/unit/views/TreeView.spec.ts

feat: variable search without filtering sections

---

src/store/actions.ts

- Functionality works & meets specifications

fix: approve action params

---

i18n.schemas.js
src/views/CartView.vue
tests/unit/views/CartView.spec.ts
tests/unit/views/__snapshots__/CartView.spec.ts.snap

fix: cleaned up cart UI

---

src/components/search/SearchComponent.vue
src/components/tree/CollapsibleTree.vue
src/store/actions.ts
src/store/getters.ts
src/views/ContentView.vue
src/views/GridView.vue
src/views/TreeView.vue
tests/unit/store/actions.spec.ts
tests/unit/store/getters.spec.ts
tests/unit/views/GridView.spec.ts
tests/unit/views/TreeView.spec.ts

feat: filter variables across subsections

---

deployment/datasets/sys_L10nString.csv

fix(l10n): fix quote escaping

---

deployment/datasets/sys_L10nString.csv

chore(l10nstring): remove duplicate line

---

src/components/facets/RangeFacet.vue

fix: slider was broken in dev, due to dev only styling injection Issue #192

---

package.json
yarn.lock

feat: version bump molgenis/components

---

src/views/CartView.vue
src/views/ContentView.vue
src/views/MainView.vue
tests/unit/views/CartView.spec.ts
tests/unit/views/MainView.spec.ts
tests/unit/views/__snapshots__/CartView.spec.ts.snap

fix: return the fixed info-bar to shop and cart

---

src/store/helpers.ts

fix: log stacktrace in tryAction

---

src/services/orderService.ts
src/store/actions.ts

fix: let ie11 be able to save an order

---

src/store/getters.ts
tests/unit/store/getters.spec.ts

fix: Replace and with or for joining subcohort filters

---

src/components/Dropdown.vue
src/scss/bootstrap-lifelines-webshop.scss
src/scss/variables.scss
src/views/OrdersView.vue
tests/unit/views/__snapshots__/OrdersView.spec.ts.snap

fix: styling errors

---

src/views/ContentView.vue
yarn.lock

chore: bump components lib to 1.4.0 and updated texttype to dark

---

src/views/OrdersView.vue

feat: add b-table busy state

---

src/components/grid/GridComponent.vue
src/repository/VariableRepository.ts
src/services/variableSetOrderService.ts
src/store/actions.ts
src/types/Variable.ts
tests/unit/components/grid/GridComponent.spec.ts
tests/unit/repository/VariableRepository.spec.ts
tests/unit/services/variableSetOrderService.spec.ts
tests/unit/store/actions.spec.ts
tests/unit/store/getters.spec.ts
tests/unit/store/helpers.spec.ts
tests/unit/store/mutations.spec.ts
tests/unit/views/CartView.spec.ts

refactor: add typing to variables

---

src/components/grid/GridComponent.vue
src/scss/bootstrap-lifelines-webshop.scss
src/store/actions.ts
src/types/Variable.ts
src/views/CartView.vue
tests/unit/store/actions.spec.ts
tests/unit/views/CartView.spec.ts
tests/unit/views/__snapshots__/CartView.spec.ts.snap

feat: set variable set line for cart

---

src/components/grid/GridComponent.vue
src/services/variableSetOrderService.ts
tests/unit/services/variableSetOrderService.spec.ts

- Fixes the sub variables that where ordered the wrong way around
- Fixes a misaligned icon

fix: variable set order and misaligned icon

---

src/components/grid/GridComponent.vue

feat: hide fields button

---

i18n.schemas.js
src/components/grid/GridComponent.vue
src/main.ts
src/store/actions.ts
src/store/getters.ts
src/store/mutations.ts
src/store/state.ts
src/types/ApplicationState.ts
src/types/Filter.ts
src/types/Getters.ts
src/views/GridView.vue
src/views/SidebarView.vue

feat: add active filter and getters for filterassessments

---

src/views/CartView.vue
tests/unit/views/CartView.spec.ts
tests/unit/views/__snapshots__/CartView.spec.ts.snap

- Sort assessment labels in CartView
- Add test to check labels are sorted
Note: Sorting in pdf is part of different reop
Story: #7249

feat: Sort assessment labels alphabetically

---

src/components/grid/GridComponent.vue

fix: removed broken vue action to open non-existing popup

---

src/views/ContentView.vue

feat: fix html characters and force release

---

src/components/grid/GridComponent.vue
tests/unit/components/grid/GridComponent.spec.ts

Closes: #289
- Check is there are variable refs before transforming elementList tpo Array to avoid null pointer

fix: #289 null pointer issue

---

README.md
deployment/lifelines
src/store/actions.ts
src/store/getters.ts
tests/e2e/resources/uiContext.js
tests/unit/store/actions.spec.ts
tests/unit/store/getters.spec.ts

fix: rename roles to proper casing

---

src/store/actions.ts
tests/unit/store/actions.spec.ts

- remove submit trigger
- update approve trigger endpoint
BREAKING CHANGE: new approve trigger endpoint

task: Update edge server endpoints

---

src/components/grid/GridComponent.vue

instead of hiding vue component in the dom, do not include it in model if its not being shown, using v-if

feat: improve variable render performance

---

src/components/grid/GridComponent.vue
tests/unit/components/grid/GridComponent.spec.ts

fix: Use lower case for nl

---

i18n.schemas.js
src/components/animations/SpinnerAnimation.vue
src/repository/VariableRepository.ts
src/store/actions.ts
src/store/mutations.ts
src/views/CartView.vue
tests/unit/fixtures/grid.ts
tests/unit/store/actions.spec.ts
tests/unit/views/CartView.spec.ts
tests/unit/views/OrdersView.spec.ts
tests/unit/views/__snapshots__/CartView.spec.ts.snap

History:
https://github.com/molgenis/molgenis-app-lifelines-webshop/pull/283
https://github.com/molgenis/molgenis-app-lifelines-webshop/pull/291

feat: select all variables from cart

---

README.md

docs: update readme with deployment instructions

---

deployment/lifelines

task: add mail settings to commander script to further automate deploy

---

src/globals/formatting.ts
tests/unit/globals/formatting.spec.ts

feat: approx values in grid

---

jest.config.js
package.json
src/router.ts
tests/e2e/specs/MainView.js
tests/unit/App.spec.ts
yarn.lock

- Update router to include router bug fixes
- Simplify routing to avoid safari routing issue
Closes #318

fix: Fix 318 safari redirect error

---

src/routes.ts

feat: added logging to debug safari routing issue

---

src/store/state.ts
tests/unit/components/facets/AgeFacet.spec.ts
tests/unit/store/actions.spec.ts
tests/unit/store/helpers.spec.ts

fix: use correct 18-64 filter value

---

src/routes.ts

Closes #327
- remove logging code that caused inf loop

fix: Fix order button broken

---

Jenkinsfile

fix: allow npx to trigger build

---

src/routes.ts
src/views/OrdersView.vue

fix: add loading bar to show approving order status

---

src/services/variableSetOrderService.ts
tests/unit/services/variableSetOrderService.spec.ts

feat:sort grid variables alphabetically

---

src/store/actions.ts
src/store/getters.ts
src/store/state.ts
src/types/ApplicationState.ts
tests/unit/store/getters.spec.ts

feat: show loading indicator during search

---

src/components/grid/GridComponent.vue
src/services/variableSetOrderService.ts
tests/unit/components/grid/GridComponent.spec.ts
tests/unit/services/variableSetOrderService.spec.ts
vue.config.js

-  Conventional commits (squash if needed)

fix: filter out subvariable row that have a zero parent

---

src/views/CartView.vue
tests/unit/views/CartView.spec.ts
tests/unit/views/__snapshots__/CartView.spec.ts.snap

fix(cart): made child relationship visible with css

---

src/repository/VariableRepository.ts

- Sub variables may be obtains via query result or variable flattening
- After flattening duplicates are removed

fix: remove duplicate subvariables

---

src/store/actions.ts
src/views/OrdersView.vue
tests/unit/App.spec.ts
tests/unit/store/actions.spec.ts
tests/unit/views/MainView.spec.ts
tests/unit/views/OrderView.spec.ts

Fix order save/update, add missing requestId field to form Fields  being posted
+ fix some unit test console errors

fix: add missing requestId field to posted formFields

---

src/store/helpers.ts
src/types/Cart.ts
tests/unit/store/actions.spec.ts
tests/unit/store/helpers.spec.ts

- Store cart selection using id's instead of names
- This enables updating the name without breaking the cart
BREAKING CHANGE: Existing carts need to be migrated to id's and chart submittion on data platform should handle cart's containing id's

feat: Switch from names to ids's in cart

---

src/store/mutations.ts
tests/unit/store/mutations.spec.ts

feat: add sub-variable aware cell/row toggle

---

src/views/CountView.vue
src/views/SidebarView.vue

Move count to make it more visible
Use bigger font size

feat: Move participant count into participant filter container

---

src/views/OrdersView.vue
tests/unit/views/__snapshots__/OrdersView.spec.ts.snap

- Add link to orders view to access cart file if user has manager rights
- Place application form link in separate column

feat: Add link to cart file

---

Jenkinsfile

Remove sauselabs e2e task form CI build

fix: Remove saucelabs

---

src/store/actions.ts

Always give manager roles write permission to updated orders
Closes #367

fix: 367 orders created by manager not shared

---

src/store/actions.ts
src/store/transforms.ts
src/views/SidebarView.vue
tests/unit/views/SidebarView.spec.ts

- Pre-select the default assessement
- Sort the assessments by name ( in filter and grid)

feat: select default assessments

---

src/components/grid/GridComponent.vue
src/repository/VariableRepository.ts
src/store/mutations.ts
tests/unit/components/grid/GridComponent.spec.ts
tests/unit/repository/VariableRepository.spec.ts
tests/unit/store/actions.spec.ts

fix: Show variable options as sorted list

---

src/views/CartView.vue

fix: hide cart spinner when cart is empty

---

src/store/actions.ts
src/views/CartView.vue
tests/unit/store/actions.spec.ts
tests/unit/views/CartView.spec.ts

- Fix spinner
- improve batch loading prerformance

fix: Show cart spinner on admin add all

---

Jenkinsfile

chore: test ci env

---

src/store/mutations.ts
tests/unit/store/mutations.spec.ts

add missing params to transform call to apply filter on select
Closes #397

fix: fix column filter
